# Helm values for cu-ms-payments
# Chart: edisonpaul4/helm-microservice-chart:1.0.3

# Configuración básica del microservicio
name: cu-ms-payments
namespace: edisonpaul4-dev
imageTag: "1" # Será sobrescrito por CI/CD con --set imageTag=<value>
port: 3000

# Variables de entorno (ConfigMap)
configMap:
  LOG_LEVEL: "debug"

# Secrets (valores en base64)
secret:
  DATABASE_PASSWORD: U3VwZXJTZWd1cm8yMDI1

# Horizontal Pod Autoscaler
hpa:
  minReplicas: 2
  maxReplicas: 6
  cpuUtilization: 90
  memoryUtilization: 90
